name: TestPROGPOE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Compile main classes
        run: javac -d ./build/main -cp src src/main/*.java

      - name: Compile test classes
        run: javac -d ./build/test -cp "src:testresources/junit-platform-console-standalone-1.6.0.jar" src/test/*.java

      - name: Run tests
        run: java -jar testresources/junit-platform-console-standalone-1.6.0.jar --class-path build/main:build/test --scan-class-path

      - name: Display test report
        run: cat junit-platform-summary.xml
